In [1]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

df = pd.DataFrame(data = iris.data, columns=iris.feature_names)

In [2]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [3]:
df[['sepal width (cm)']]

sepal width (cm)
0                 3.5
1                 3.0
2                 3.2
3                 3.1
4                 3.6
..                ...
145               3.0
146               2.5
147               3.0
148               3.4
149               3.0

[150 rows x 1 columns]

In [5]:
df.iloc[1]

sepal length (cm)    4.9
sepal width (cm)     3.0
petal length (cm)    1.4
petal width (cm)     0.2
Name: 1, dtype: float64

In [6]:
df.iloc[:, 1]

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal width (cm), Length: 150, dtype: float64

In [7]:
df.iloc[1,2]

1.4

In [8]:
df.iloc[[1,2]]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [11]:
df[df['sepal length (cm)'] == 4.9]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                  4.9               3.0                1.4               0.2
9                  4.9               3.1                1.5               0.1
34                 4.9               3.1                1.5               0.2
37                 4.9               3.6                1.4               0.1
57                 4.9               2.4                3.3               1.0
106                4.9               2.5                4.5               1.7

In [14]:
df.iloc[[1,2]]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [16]:
df = pd.DataFrame({'Test' : ['v', 's', 's', 's', 'va', 'va', 'v']})
e_df = pd.get_dummies(df['Test'])

In [17]:
e_df

s      v     va
0  False   True  False
1   True  False  False
2   True  False  False
3   True  False  False
4  False  False   True
5  False  False   True
6  False   True  False

In [18]:
df = pd.DataFrame(data = iris.data, columns=iris.feature_names)

In [20]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [24]:
df.groupby('sepal length (cm)').max()

sepal width (cm)  petal length (cm)  petal width (cm)
sepal length (cm)                                                       
4.3                             3.0                1.1               0.1
4.4                             3.2                1.4               0.2
4.5                             2.3                1.3               0.3
4.6                             3.6                1.5               0.3
4.7                             3.2                1.6               0.2
4.8                             3.4                1.9               0.3
4.9                             3.6                4.5               1.7
5.0                             3.6                3.5               1.0
5.1                             3.8                3.0               1.1
5.2                             4.1                3.9               1.4
5.3                             3.7                1.5               0.2
5.4                             3.9                4.5               1.5
5.5                             4.2                4.4               1.3
5.6                             3.0                4.9               2.0
5.7                             4.4                5.0               2.0
5.8                             4.0                5.1               2.4
5.9                             3.2                5.1               1.8
6.0                             3.4                5.1               1.8
6.1                             3.0                5.6               1.8
6.2                             3.4                5.4               2.3
6.3                             3.4                6.0               2.5
6.4                             3.2                5.6               2.3
6.5                             3.2                5.8               2.2
6.6                             3.0                4.6               1.4
6.7                             3.3                5.8               2.5
6.8                             3.2                5.9               2.3
6.9                             3.2                5.7               2.3
7.0                             3.2                4.7               1.4
7.1                             3.0                5.9               2.1
7.2                             3.6                6.1               2.5
7.3                             2.9                6.3               1.8
7.4                             2.8                6.1               1.9
7.6                             3.0                6.6               2.1
7.7                             3.8                6.9               2.3
7.9                             3.8                6.4               2.0

In [25]:
a = df[['sepal length (cm)']]

In [33]:
a = a.sort_values(by = 'sepal length (cm)')

In [35]:
a = df[['sepal length (cm)']]
b = df[['sepal width (cm)']]

In [38]:
c = pd.concat([a,b], axis = 1)

In [39]:
c

sepal length (cm)  sepal width (cm)
0                  5.1               3.5
1                  4.9               3.0
2                  4.7               3.2
3                  4.6               3.1
4                  5.0               3.6
..                 ...               ...
145                6.7               3.0
146                6.3               2.5
147                6.5               3.0
148                6.2               3.4
149                5.9               3.0

[150 rows x 2 columns]

In [41]:
a = pd.DataFrame({'x' : ['a', 'b', 'c'],
                  'y' : [1,2,3]})
b = pd.DataFrame({'x' : ['c', 'b', 'd'],
                  'z' : [4,5,6]})

In [42]:
pd.merge(a, b, how = 'left', on = 'x')

x  y    z
0  a  1  NaN
1  b  2  5.0
2  c  3  4.0

In [43]:
pd.merge(a,b,how='inner',on='x')

x  y  z
0  b  2  5
1  c  3  4

In [52]:
na_test = pd.merge(a,b,how='outer',on='x')

In [45]:
import numpy as np

In [46]:
test = np.array([1,5,2,3,4,5])

In [48]:
np.where(test>3)

(array([1, 4, 5], dtype=int64),)

In [51]:
np.where(test>3, 4, test) # 3보다 큰 값은 4로 대체 크지 않다면 값 그대로

array([1, 4, 2, 3, 4, 4])

In [53]:
na_test.isna()

x      y      z
0  False  False   True
1  False  False  False
2  False  False  False
3  False   True  False

In [54]:
na_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x       4 non-null      object 
 1   y       3 non-null      float64
 2   z       3 non-null      float64
dtypes: float64(2), object(1)
memory usage: 224.0+ bytes


In [55]:
test = na_test.dropna()

In [56]:
test

x    y    z
1  b  2.0  5.0
2  c  3.0  4.0

In [67]:
test1 = na_test.drop('x', axis=1)

In [68]:
test1

y    z
0  1.0  NaN
1  2.0  5.0
2  3.0  4.0
3  NaN  6.0

In [71]:
na_test.fillna('abc', axis=0)

x    y    z
0  a  1.0  abc
1  b  2.0  5.0
2  c  3.0  4.0
3  d  abc  6.0

In [72]:
a = ['1', '2', '3', '4' ,'5']

In [76]:
b = int(a[0])

In [77]:
b

1

In [78]:
from sklearn.preprocessing import MinMaxScaler

test = np.array([1,4,5,4,5,8,9,3,2])

In [82]:
re = test.reshape(-1,1)
s = MinMaxScaler().fit_transform(re)
s.flatten()

array([0.   , 0.375, 0.5  , 0.375, 0.5  , 0.875, 1.   , 0.25 , 0.125])

In [83]:
def z_score(data) :
    return (data-np.mean(data)) / np.std(data, ddof=1)

In [84]:
z_score(test)

array([-1.36572672, -0.2133948 ,  0.17071584, -0.2133948 ,  0.17071584,
        1.32304776,  1.7071584 , -0.59750544, -0.98161608])

In [87]:
a = np.random.choice(test, size = 10, replace = True)
a

array([4, 9, 9, 9, 1, 2, 4, 1, 4, 4])

In [95]:
b = [1,2,3,4,5,6,7,8]
c = [2,5,8,3,1,6,7,4]

In [89]:
from scipy.stats import trim_mean

In [92]:
trim_mean(b, 0.1)

4.5

In [96]:
trim_mean(c, 0.1)

4.5

In [97]:
a = [1,2,3,4,5,2,3,4,5,6,3,2,1]

In [100]:
np.bincount(a).argmax()

2

In [103]:
a = [1,2,3,4,10]

In [104]:
np.ptp(a)

9